name: GitHub Action for Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
        with:
           branch: retype
           update-branch: true
